-- Hand-curated raw merchant_category → CanonicalCategory mappings.
-- Loaded once if category_aliases is empty. Idempotent insert via ON CONFLICT.
INSERT INTO category_aliases (raw_value, canonical_category, source, confidence, sample_transaction_count, created_at, updated_at)
VALUES
  -- Groceries / supermarkets
  ('groceries', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('grocery', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('supermarket', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('supermarkets', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('food', 'GROCERIES_SUPERMARKETS', 'SEED', 0.8, 0, NOW(), NOW()),
  ('whole foods', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('trader joes', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('trader joe''s', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('safeway', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('kroger', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('publix', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('wegmans', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('aldi', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('h-e-b', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('heb', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('shoprite', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('food lion', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('giant', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('stop & shop', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('stop and shop', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('sprouts', 'GROCERIES_SUPERMARKETS', 'SEED', 1.0, 0, NOW(), NOW()),

  -- Warehouse clubs
  ('warehouse club', 'WAREHOUSE_CLUB', 'SEED', 1.0, 0, NOW(), NOW()),
  ('wholesale club', 'WAREHOUSE_CLUB', 'SEED', 1.0, 0, NOW(), NOW()),
  ('costco', 'WAREHOUSE_CLUB', 'SEED', 1.0, 0, NOW(), NOW()),
  ('sams club', 'WAREHOUSE_CLUB', 'SEED', 1.0, 0, NOW(), NOW()),
  ('sam''s club', 'WAREHOUSE_CLUB', 'SEED', 1.0, 0, NOW(), NOW()),
  ('bjs', 'WAREHOUSE_CLUB', 'SEED', 1.0, 0, NOW(), NOW()),
  ('bj''s', 'WAREHOUSE_CLUB', 'SEED', 1.0, 0, NOW(), NOW()),
  ('bjs wholesale', 'WAREHOUSE_CLUB', 'SEED', 1.0, 0, NOW(), NOW()),

  -- Dining
  ('restaurant', 'DINING_RESTAURANTS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('restaurants', 'DINING_RESTAURANTS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('dining', 'DINING_RESTAURANTS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('cafe', 'DINING_RESTAURANTS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('coffee', 'DINING_RESTAURANTS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('coffee shop', 'DINING_RESTAURANTS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('starbucks', 'DINING_RESTAURANTS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('chipotle', 'DINING_RESTAURANTS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('sweetgreen', 'DINING_RESTAURANTS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('bar', 'DINING_RESTAURANTS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('bars', 'DINING_RESTAURANTS', 'SEED', 1.0, 0, NOW(), NOW()),

  -- Fast food / delivery
  ('fast food', 'FAST_FOOD', 'SEED', 1.0, 0, NOW(), NOW()),
  ('mcdonalds', 'FAST_FOOD', 'SEED', 1.0, 0, NOW(), NOW()),
  ('mcdonald''s', 'FAST_FOOD', 'SEED', 1.0, 0, NOW(), NOW()),
  ('burger king', 'FAST_FOOD', 'SEED', 1.0, 0, NOW(), NOW()),
  ('taco bell', 'FAST_FOOD', 'SEED', 1.0, 0, NOW(), NOW()),
  ('wendy''s', 'FAST_FOOD', 'SEED', 1.0, 0, NOW(), NOW()),
  ('wendys', 'FAST_FOOD', 'SEED', 1.0, 0, NOW(), NOW()),
  ('chick-fil-a', 'FAST_FOOD', 'SEED', 1.0, 0, NOW(), NOW()),
  ('chick fil a', 'FAST_FOOD', 'SEED', 1.0, 0, NOW(), NOW()),
  ('doordash', 'FAST_FOOD', 'SEED', 1.0, 0, NOW(), NOW()),
  ('uber eats', 'FAST_FOOD', 'SEED', 1.0, 0, NOW(), NOW()),
  ('ubereats', 'FAST_FOOD', 'SEED', 1.0, 0, NOW(), NOW()),
  ('grubhub', 'FAST_FOOD', 'SEED', 1.0, 0, NOW(), NOW()),
  ('seamless', 'FAST_FOOD', 'SEED', 1.0, 0, NOW(), NOW()),
  ('postmates', 'FAST_FOOD', 'SEED', 1.0, 0, NOW(), NOW()),

  -- Gas
  ('gas', 'GAS_STATIONS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('gas station', 'GAS_STATIONS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('gas stations', 'GAS_STATIONS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('fuel', 'GAS_STATIONS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('shell', 'GAS_STATIONS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('chevron', 'GAS_STATIONS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('exxon', 'GAS_STATIONS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('mobil', 'GAS_STATIONS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('bp', 'GAS_STATIONS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('sunoco', 'GAS_STATIONS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('valero', 'GAS_STATIONS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('citgo', 'GAS_STATIONS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('marathon', 'GAS_STATIONS', 'SEED', 1.0, 0, NOW(), NOW()),

  -- EV charging
  ('ev charging', 'EV_CHARGING', 'SEED', 1.0, 0, NOW(), NOW()),
  ('tesla supercharger', 'EV_CHARGING', 'SEED', 1.0, 0, NOW(), NOW()),
  ('electrify america', 'EV_CHARGING', 'SEED', 1.0, 0, NOW(), NOW()),
  ('chargepoint', 'EV_CHARGING', 'SEED', 1.0, 0, NOW(), NOW()),
  ('evgo', 'EV_CHARGING', 'SEED', 1.0, 0, NOW(), NOW()),

  -- Online retail
  ('online retail', 'ONLINE_RETAIL', 'SEED', 1.0, 0, NOW(), NOW()),
  ('online shopping', 'ONLINE_RETAIL', 'SEED', 1.0, 0, NOW(), NOW()),
  ('amazon', 'ONLINE_RETAIL', 'SEED', 1.0, 0, NOW(), NOW()),
  ('amazon.com', 'ONLINE_RETAIL', 'SEED', 1.0, 0, NOW(), NOW()),
  ('target.com', 'ONLINE_RETAIL', 'SEED', 1.0, 0, NOW(), NOW()),
  ('walmart.com', 'ONLINE_RETAIL', 'SEED', 1.0, 0, NOW(), NOW()),
  ('best buy', 'ONLINE_RETAIL', 'SEED', 0.7, 0, NOW(), NOW()),
  ('ebay', 'ONLINE_RETAIL', 'SEED', 1.0, 0, NOW(), NOW()),
  ('etsy', 'ONLINE_RETAIL', 'SEED', 1.0, 0, NOW(), NOW()),
  ('shopping', 'ONLINE_RETAIL', 'SEED', 0.6, 0, NOW(), NOW()),

  -- Drugstores
  ('drugstore', 'DRUGSTORES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('drug store', 'DRUGSTORES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('drugstores', 'DRUGSTORES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('pharmacy', 'DRUGSTORES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('cvs', 'DRUGSTORES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('walgreens', 'DRUGSTORES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('rite aid', 'DRUGSTORES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('duane reade', 'DRUGSTORES', 'SEED', 1.0, 0, NOW(), NOW()),

  -- Travel
  ('travel', 'TRAVEL_GENERAL', 'SEED', 1.0, 0, NOW(), NOW()),
  ('airline', 'AIRLINES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('airlines', 'AIRLINES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('delta', 'AIRLINES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('united airlines', 'AIRLINES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('american airlines', 'AIRLINES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('southwest', 'AIRLINES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('jetblue', 'AIRLINES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('alaska airlines', 'AIRLINES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('hotel', 'HOTELS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('hotels', 'HOTELS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('marriott', 'HOTELS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('hilton', 'HOTELS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('hyatt', 'HOTELS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('ihg', 'HOTELS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('airbnb', 'HOTELS', 'SEED', 1.0, 0, NOW(), NOW()),
  ('chase travel', 'TRAVEL_PORTAL', 'SEED', 1.0, 0, NOW(), NOW()),
  ('amex travel', 'TRAVEL_PORTAL', 'SEED', 1.0, 0, NOW(), NOW()),
  ('capital one travel', 'TRAVEL_PORTAL', 'SEED', 1.0, 0, NOW(), NOW()),

  -- Rideshare
  ('rideshare', 'RIDESHARE', 'SEED', 1.0, 0, NOW(), NOW()),
  ('uber', 'RIDESHARE', 'SEED', 1.0, 0, NOW(), NOW()),
  ('lyft', 'RIDESHARE', 'SEED', 1.0, 0, NOW(), NOW()),

  -- Streaming
  ('streaming', 'STREAMING', 'SEED', 1.0, 0, NOW(), NOW()),
  ('netflix', 'STREAMING', 'SEED', 1.0, 0, NOW(), NOW()),
  ('disney+', 'STREAMING', 'SEED', 1.0, 0, NOW(), NOW()),
  ('disney plus', 'STREAMING', 'SEED', 1.0, 0, NOW(), NOW()),
  ('hulu', 'STREAMING', 'SEED', 1.0, 0, NOW(), NOW()),
  ('spotify', 'STREAMING', 'SEED', 1.0, 0, NOW(), NOW()),
  ('apple tv+', 'STREAMING', 'SEED', 1.0, 0, NOW(), NOW()),
  ('apple music', 'STREAMING', 'SEED', 1.0, 0, NOW(), NOW()),
  ('youtube premium', 'STREAMING', 'SEED', 1.0, 0, NOW(), NOW()),
  ('hbo max', 'STREAMING', 'SEED', 1.0, 0, NOW(), NOW()),

  -- Utilities
  ('utilities', 'UTILITIES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('utility', 'UTILITIES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('electric', 'UTILITIES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('gas utility', 'UTILITIES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('water', 'UTILITIES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('internet', 'UTILITIES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('verizon', 'UTILITIES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('at&t', 'UTILITIES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('comcast', 'UTILITIES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('xfinity', 'UTILITIES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('eversource', 'UTILITIES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('coned', 'UTILITIES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('con edison', 'UTILITIES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('pg&e', 'UTILITIES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('pge', 'UTILITIES', 'SEED', 1.0, 0, NOW(), NOW()),

  -- Transit
  ('transit', 'TRANSIT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('mta', 'TRANSIT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('bart', 'TRANSIT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('mbta', 'TRANSIT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('wmata', 'TRANSIT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('toll', 'TRANSIT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('tolls', 'TRANSIT', 'SEED', 1.0, 0, NOW(), NOW()),

  -- Entertainment
  ('entertainment', 'ENTERTAINMENT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('movie', 'ENTERTAINMENT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('movies', 'ENTERTAINMENT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('amc', 'ENTERTAINMENT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('ticketmaster', 'ENTERTAINMENT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('stubhub', 'ENTERTAINMENT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('concert', 'ENTERTAINMENT', 'SEED', 1.0, 0, NOW(), NOW()),

  -- Home improvement
  ('home improvement', 'HOME_IMPROVEMENT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('home depot', 'HOME_IMPROVEMENT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('lowes', 'HOME_IMPROVEMENT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('lowe''s', 'HOME_IMPROVEMENT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('ace hardware', 'HOME_IMPROVEMENT', 'SEED', 1.0, 0, NOW(), NOW()),
  ('menards', 'HOME_IMPROVEMENT', 'SEED', 1.0, 0, NOW(), NOW()),

  -- Department stores
  ('department store', 'DEPARTMENT_STORES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('department stores', 'DEPARTMENT_STORES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('macys', 'DEPARTMENT_STORES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('macy''s', 'DEPARTMENT_STORES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('nordstrom', 'DEPARTMENT_STORES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('kohls', 'DEPARTMENT_STORES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('kohl''s', 'DEPARTMENT_STORES', 'SEED', 1.0, 0, NOW(), NOW()),
  ('target', 'DEPARTMENT_STORES', 'SEED', 0.8, 0, NOW(), NOW()),
  ('walmart', 'DEPARTMENT_STORES', 'SEED', 0.8, 0, NOW(), NOW())
ON CONFLICT (raw_value) DO NOTHING;
