name: iOS Build

on:
  push:
    branches:
      - main
    paths:
      - 'CredTrack/**'
  pull_request:
    branches:
      - main
    paths:
      - 'CredTrack/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        working-directory: CredTrack
        run: |
          xcodebuild clean build \
            -project CredTrack.xcodeproj \
            -scheme CredTrack \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
